name: Update gist!

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Update activity from AniList
        uses: slashedzer0/neko-box@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          ANILIST_USERNAME: ${{ secrets.ANILIST_USERNAME }}
